vim.opt.undodir = os.getenv("HOME") .. "/.config/nvim/undos"
vim.opt.swapfile = false
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.undofile = true
vim.opt.updatetime =100 
vim.opt.termguicolors = true 
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.colorcolumn = '120'
vim.opt.list = true 
vim.opt.encoding = 'UTF-8' 
vim.opt.scrolloff = 8 
vim.opt.showmatch = true 
vim.opt.ignorecase = true 
vim.opt.smartcase  = true 
vim.opt.hlsearch = true 
vim.opt.incsearch = true 
vim.opt.wrap = false 
vim.opt.foldlevel = 99
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.api.nvim_set_hl(0, 'LineNrAbove', { fg='grey'})
vim.api.nvim_set_hl(0, 'LineNr', { fg='#ff7600', bg='black', bold=true })
vim.api.nvim_set_hl(0, 'LineNrBelow', { fg='grey'})
-- vim.opt.syntax = 'enable' 
